nohup: ignoring input
/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/privacy_engine.py:95: UserWarning: Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_mode`` turned on.
  warnings.warn(
01/22/2025 11:29:18:WARNING:Ignoring drop_last as it is not compatible with DPDataLoader.
01/22/2025 11:29:18:DEBUG:Opened insecure gRPC connection (no certificates were passed)
01/22/2025 11:29:18:DEBUG:ChannelConnectivity.IDLE
01/22/2025 11:29:18:DEBUG:ChannelConnectivity.CONNECTING
01/22/2025 11:29:18:DEBUG:ChannelConnectivity.READY
nohup: ignoring input
/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/privacy_engine.py:95: UserWarning: Secure RNG turned off. This is perfectly fine for experimentation as it allows for much faster training performance, but remember to turn it on and retrain one last time before production with ``secure_mode`` turned on.
  warnings.warn(
01/22/2025 11:30:20:WARNING:Ignoring drop_last as it is not compatible with DPDataLoader.
01/22/2025 11:30:20:DEBUG:Opened insecure gRPC connection (no certificates were passed)
01/22/2025 11:30:20:DEBUG:ChannelConnectivity.IDLE
01/22/2025 11:30:20:DEBUG:ChannelConnectivity.READY
[92mINFO [0m:      
01/22/2025 11:30:53:INFO:
[92mINFO [0m:      [RUN 0, ROUND ]
01/22/2025 11:30:53:INFO:[RUN 0, ROUND ]
[92mINFO [0m:      Received: train message c95ac248-119f-420e-b569-e3535f8dd177
01/22/2025 11:30:53:INFO:Received: train message c95ac248-119f-420e-b569-e3535f8dd177
/home/dgxuser16/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1359: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
[92mINFO [0m:      Sent reply
01/22/2025 11:33:57:INFO:Sent reply
[92mINFO [0m:      
01/22/2025 11:35:48:INFO:
[92mINFO [0m:      [RUN 0, ROUND ]
01/22/2025 11:35:48:INFO:[RUN 0, ROUND ]
[92mINFO [0m:      Received: evaluate message 8c96f819-50b6-431b-a8e7-17712e575f93
01/22/2025 11:35:48:INFO:Received: evaluate message 8c96f819-50b6-431b-a8e7-17712e575f93
[92mINFO [0m:      Sent reply
01/22/2025 11:36:31:INFO:Sent reply
[92mINFO [0m:      
01/22/2025 11:36:58:INFO:
[92mINFO [0m:      [RUN 0, ROUND ]
01/22/2025 11:36:58:INFO:[RUN 0, ROUND ]
[92mINFO [0m:      Received: train message 15e7c249-bd79-4205-aced-1f6ef04e265e
01/22/2025 11:36:58:INFO:Received: train message 15e7c249-bd79-4205-aced-1f6ef04e265e
/home/dgxuser16/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1359: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
[92mINFO [0m:      Sent reply
01/22/2025 11:40:06:INFO:Sent reply
[92mINFO [0m:      
01/22/2025 11:41:55:INFO:
[92mINFO [0m:      [RUN 0, ROUND ]
01/22/2025 11:41:55:INFO:[RUN 0, ROUND ]
[92mINFO [0m:      Received: evaluate message 351f3c5d-d46e-43ac-8ef2-1d475e9e751f
01/22/2025 11:41:55:INFO:Received: evaluate message 351f3c5d-d46e-43ac-8ef2-1d475e9e751f
[92mINFO [0m:      Sent reply
01/22/2025 11:42:32:INFO:Sent reply
[92mINFO [0m:      
01/22/2025 11:42:42:INFO:
[92mINFO [0m:      [RUN 0, ROUND ]
01/22/2025 11:42:42:INFO:[RUN 0, ROUND ]
[92mINFO [0m:      Received: train message 3a22253b-eb0a-4ef9-9f4e-cc0bc3e22abd
01/22/2025 11:42:42:INFO:Received: train message 3a22253b-eb0a-4ef9-9f4e-cc0bc3e22abd
/home/dgxuser16/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1359: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
[91mERROR [0m:     Client raised an exception.
Traceback (most recent call last):
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client_2.py", line 147, in fit
    epsilon = train(
  File "client_2.py", line 85, in train
    optimizer.step()
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 518, in step
    if self.pre_step():
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 499, in pre_step
    self.clip_and_accumulate()
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 412, in clip_and_accumulate
    grad = contract("i,i...", per_sample_clip_factor, grad_sample)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 507, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 573, in _core_contract
    new_view = _tensordot(*tmp_operands, axes=(tuple(left_pos), tuple(right_pos)), backend=backend)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/sharing.py", line 131, in cached_tensordot
    return tensordot(x, y, axes, backend=backend)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 374, in _tensordot
    return fn(x, y, axes=axes)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/backends/torch.py", line 54, in tensordot
    return torch.tensordot(x, y, dims=axes)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/torch/functional.py", line 1193, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
01/22/2025 11:42:45:ERROR:Client raised an exception.
Traceback (most recent call last):
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client_2.py", line 147, in fit
    epsilon = train(
  File "client_2.py", line 85, in train
    optimizer.step()
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 518, in step
    if self.pre_step():
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 499, in pre_step
    self.clip_and_accumulate()
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 412, in clip_and_accumulate
    grad = contract("i,i...", per_sample_clip_factor, grad_sample)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 507, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 573, in _core_contract
    new_view = _tensordot(*tmp_operands, axes=(tuple(left_pos), tuple(right_pos)), backend=backend)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/sharing.py", line 131, in cached_tensordot
    return tensordot(x, y, axes, backend=backend)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 374, in _tensordot
    return fn(x, y, axes=axes)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/backends/torch.py", line 54, in tensordot
    return torch.tensordot(x, y, dims=axes)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/torch/functional.py", line 1193, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
01/22/2025 11:42:45:DEBUG:gRPC channel closed
Error importing huggingface_hub.hf_api: No module named 'tqdm'
Error importing huggingface_hub.hf_api: No module named 'tqdm'
Epsilon = 1.37

{'loss': [183.98990601301193], 'accuracy': [0.49335418295543393], 'auc': [0.5195222601061145]}

Epsilon = 1.88

{'loss': [183.98990601301193, 172.18215227127075], 'accuracy': [0.49335418295543393, 0.4988272087568413], 'auc': [0.5195222601061145, 0.5699639102911909]}

Traceback (most recent call last):
  File "client_2.py", line 183, in <module>
    fl.client.start_client(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/app.py", line 291, in start_client
    _start_client_internal(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/app.py", line 503, in _start_client_internal
    raise ex
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/app.py", line 496, in _start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client_2.py", line 147, in fit
    epsilon = train(
  File "client_2.py", line 85, in train
    optimizer.step()
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 518, in step
    if self.pre_step():
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 499, in pre_step
    self.clip_and_accumulate()
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opacus/optimizers/optimizer.py", line 412, in clip_and_accumulate
    grad = contract("i,i...", per_sample_clip_factor, grad_sample)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 507, in contract
    return _core_contract(operands, contraction_list, backend=backend, **einsum_kwargs)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 573, in _core_contract
    new_view = _tensordot(*tmp_operands, axes=(tuple(left_pos), tuple(right_pos)), backend=backend)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/sharing.py", line 131, in cached_tensordot
    return tensordot(x, y, axes, backend=backend)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/contract.py", line 374, in _tensordot
    return fn(x, y, axes=axes)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/opt_einsum/backends/torch.py", line 54, in tensordot
    return torch.tensordot(x, y, dims=axes)
  File "/home/dgxuser16/.local/lib/python3.8/site-packages/torch/functional.py", line 1193, in tensordot
    return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
